# Generated by Django 5.2.1 on 2025-06-21 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_education_options_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_gallery/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='profiles.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
