# Generated by Django 5.2.1 on 2025-06-22 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Stores the original name of the file as uploaded by the user.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
