# Generated by Django 5.2.1 on 2025-06-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Art', 'Art'), ('Food', 'Food'), ('Travel', 'Travel'), ('Photography', 'Photography'), ('Design', 'Design')], max_length=50, null=True),
        ),
    ]
