# Generated by Django 5.2.1 on 2025-06-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_remove_postimage_image_postimage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
